### ISSUE TITLE
Falta de memoria ao processar arquivo Estabelecimento0.zip

### ISSUE THREAD

**Issue by jonathands** [elizandrodantas/cnpj-data-go#1]
Estou rodando o projeto para montar o banco em SQLite e esta sendo uma mão na roda (Obrigado!), porém tive alguns problemas... sempre que chegava no Estabelecimentos0 ele acabava matando o processo , notei que nos últimos meses esse arquivo esta vindo bem inchado - zipado esta com 1.1gb... 

Fui ver no dmesg ele traz:

`[617411.452004] Out of memory: Killed process 3358678 (cnpj-data-go) total-vm:15473708kB, anon-rss:13309368kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:26316kB oom_score_adj:0
`
Estou no Mint , com 20Gb de memoria acho que deveria ser o suficiente

Notei que o programa descompacta e depois carrega o arquivo que esta processando na memoria, alterei aqui meio que no facão  para fazer stream do arquivo (não entendo nada de GO) e baixei o tamanho do BATCH_INSERT para 50, demorou um bocado mas rodou.

Talvez seja interessante mudar o programa para fazer stream no lugar do getData carregar tudo na memória

**Comment by elizandrodantas** [comment]
boa.
